import {default as common} from './common.json';
import {default as errors} from './errors.json';
import {default as auth} from './auth.json';
import {default as profile} from './profile.json';
import {default as alerts} from './alerts.json';
import {default as calendar} from './calendar.json';
import {default as settings} from './settings.json';
import {default as invoices} from './invoices.json';
import {default as clients} from './clients.json';
import {default as sessions} from './sessions.json';
export default {common,errors,auth,profile,alerts,calendar,settings,invoices,clients,sessions};