name: depoy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ dev ]
  #pull_request:
    #branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: self-hosted
    env:
      CI: false
      NODE_ENV: development
      REACT_APP_BASE_URL: https://liveright-dev.madebycolorelephant.com
      REACT_APP_BASE_API_URL: https://api.liveright-dev.madebycolorelephant.com


    steps:

      - uses: actions/checkout@v2

      - name: Run yarn install
        run: yarn install
      - name: Run yarn build
        run: yarn build

      # Runs a set of commands using the runners shell
      - name: Deploy to dev
        run: |
          echo depoy to dev env
          cp -r build/* /var/www/dev/front
